<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
   <testsuite name="TestAssets.PB-ParabankServices-v3_tst"
               tests="30"
               id="1"
               package=""
               time="1.633"
               hostname="CD-LYAO-02"
               timestamp="2024-04-11T14:24:14"
               failures="30"
               errors="0">
      <properties/>
      <testcase name="Test Suite: Retrieve Accounts and Validate/Set-Up Tests/Set-Up 1: cleanDB"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.375"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">Invalid WSDL. Connection refused: connect

Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.</failure>
      </testcase>
      <testcase name="Test Suite: Retrieve Accounts and Validate/Set-Up Tests/Set-Up 2: Stop Coverage Session"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.035"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Connection refused: connect" type="Failure">com.parasoft.api.tool.CustomToolException: Connection refused: connect&#xD;
	at StopCoverageSession.execute(StopCoverageSession.java:51)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:267)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:1)&#xD;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)&#xD;
	at java.base/java.lang.Thread.run(Thread.java:829)&#xD;
Caused by: java.net.ConnectException: Connection refused: connect&#xD;
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)&#xD;
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:615)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:563)&#xD;
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:509)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:604)&#xD;
	at java.base/sun.net.www.http.HttpClient.&lt;init&gt;(HttpClient.java:277)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:376)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:397)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1258)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1192)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1086)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1020)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1597)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1525)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderFields(HttpURLConnection.java:3156)&#xD;
	at CoverageAgentController.getResponse(CoverageAgentController.java:238)&#xD;
	at CoverageAgentController.execute(CoverageAgentController.java:88)&#xD;
	at StopCoverageSession.execute(StopCoverageSession.java:47)&#xD;
	... 6 more&#xD;
[Nested Exception] java.net.ConnectException: Connection refused: connect&#xD;
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)&#xD;
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:615)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:563)&#xD;
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:509)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:604)&#xD;
	at java.base/sun.net.www.http.HttpClient.&lt;init&gt;(HttpClient.java:277)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:376)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:397)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1258)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1192)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1086)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1020)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1597)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1525)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderFields(HttpURLConnection.java:3156)&#xD;
	at CoverageAgentController.getResponse(CoverageAgentController.java:238)&#xD;
	at CoverageAgentController.execute(CoverageAgentController.java:88)&#xD;
	at StopCoverageSession.execute(StopCoverageSession.java:47)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:267)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:1)&#xD;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)&#xD;
	at java.base/java.lang.Thread.run(Thread.java:829)&#xD;
</failure>
      </testcase>
      <testcase name="Test Suite: Retrieve Accounts and Validate/Set-Up Tests/Set-Up 3: Start Coverage Session"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.014"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Connection refused: connect" type="Failure">com.parasoft.api.tool.CustomToolException: Connection refused: connect&#xD;
	at StartCoverageSession.execute(StartCoverageSession.java:51)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:267)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:1)&#xD;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)&#xD;
	at java.base/java.lang.Thread.run(Thread.java:829)&#xD;
Caused by: java.net.ConnectException: Connection refused: connect&#xD;
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)&#xD;
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:615)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:563)&#xD;
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:509)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:604)&#xD;
	at java.base/sun.net.www.http.HttpClient.&lt;init&gt;(HttpClient.java:277)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:376)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:397)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1258)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1192)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1086)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1020)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1597)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1525)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderFields(HttpURLConnection.java:3156)&#xD;
	at CoverageAgentController.getResponse(CoverageAgentController.java:238)&#xD;
	at CoverageAgentController.execute(CoverageAgentController.java:88)&#xD;
	at StartCoverageSession.execute(StartCoverageSession.java:47)&#xD;
	... 6 more&#xD;
[Nested Exception] java.net.ConnectException: Connection refused: connect&#xD;
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)&#xD;
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:615)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:563)&#xD;
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:509)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:604)&#xD;
	at java.base/sun.net.www.http.HttpClient.&lt;init&gt;(HttpClient.java:277)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:376)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:397)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1258)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1192)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1086)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1020)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1597)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1525)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderFields(HttpURLConnection.java:3156)&#xD;
	at CoverageAgentController.getResponse(CoverageAgentController.java:238)&#xD;
	at CoverageAgentController.execute(CoverageAgentController.java:88)&#xD;
	at StartCoverageSession.execute(StartCoverageSession.java:47)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:267)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:1)&#xD;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)&#xD;
	at java.base/java.lang.Thread.run(Thread.java:829)&#xD;
</failure>
      </testcase>
      <testcase name="Test Suite: Retrieve Accounts and Validate/Scenario: Get Accounts/Test 1: Start Coverage Test: Get Accounts"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.013"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Connection refused: connect" type="Failure">com.parasoft.api.tool.CustomToolException: Connection refused: connect&#xD;
	at StartCoverageTest.execute(StartCoverageTest.java:51)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:267)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:1)&#xD;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)&#xD;
	at java.base/java.lang.Thread.run(Thread.java:829)&#xD;
</failure>
      </testcase>
      <testcase name="Test Suite: Retrieve Accounts and Validate/Scenario: Get Accounts/Test 2: login"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.042"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Retrieve Accounts and Validate/Scenario: Get Accounts/Test 3: getAccounts"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.077"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">[customerId] No Data Source column named Test 1: id[1]
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

No Data Source column named Test 1: id[1]
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Retrieve Accounts and Validate/Scenario: Open Account/Test 1: Start Coverage Test: Open Account"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.029"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Connection refused: connect" type="Failure">com.parasoft.api.tool.CustomToolException: Connection refused: connect&#xD;
	at StartCoverageTest.execute(StartCoverageTest.java:51)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:267)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:1)&#xD;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)&#xD;
	at java.base/java.lang.Thread.run(Thread.java:829)&#xD;
</failure>
      </testcase>
      <testcase name="Test Suite: Retrieve Accounts and Validate/Scenario: Open Account/Test 2: login"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.050"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Retrieve Accounts and Validate/Scenario: Open Account/Test 3: getAccounts"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.055"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">[customerId] No Data Source column named Test 1: id[1]
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

No Data Source column named Test 1: id[1]
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Retrieve Accounts and Validate/Scenario: Open Account/Test 4: createAccount"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.075"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">Invalid WSDL. Connection refused: connect

[customerId] No Data Source column named Test 1: id[1]
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

No Data Source column named Test 1: id[1]
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

[fromAccountId] No Data Source column named Test 3: id[1]
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

No Data Source column named Test 3: id[1]
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.</failure>
      </testcase>
      <testcase name="Test Suite: Retrieve Accounts and Validate/Scenario: Open Account/Test 5: getAccounts 2"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.057"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">[customerId] No Data Source column named Test 1: id[1]
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

No Data Source column named Test 1: id[1]
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Retrieve Accounts and Validate/Scenario: Withdrawl and Transfer/Test 1: Start Coverage Test: Withdrawl and Transfer[withdrawTransferValues (row 1)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.029"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="DataSource: withdrawTransferValues (row 1): Connection refused: connect"
                   type="Failure">com.parasoft.api.tool.CustomToolException: Connection refused: connect&#xD;
	at StartCoverageTest.execute(StartCoverageTest.java:51)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:267)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:1)&#xD;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)&#xD;
	at java.base/java.lang.Thread.run(Thread.java:829)&#xD;
</failure>
      </testcase>
      <testcase name="Test Suite: Retrieve Accounts and Validate/Scenario: Withdrawl and Transfer/Test 1: Start Coverage Test: Withdrawl and Transfer[withdrawTransferValues (row 2)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.017"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="DataSource: withdrawTransferValues (row 2): Connection refused: connect"
                   type="Failure">com.parasoft.api.tool.CustomToolException: Connection refused: connect&#xD;
	at StartCoverageTest.execute(StartCoverageTest.java:51)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:267)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:1)&#xD;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)&#xD;
	at java.base/java.lang.Thread.run(Thread.java:829)&#xD;
</failure>
      </testcase>
      <testcase name="Test Suite: Retrieve Accounts and Validate/Scenario: Withdrawl and Transfer/Test 1: Start Coverage Test: Withdrawl and Transfer[withdrawTransferValues (row 3)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.019"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="DataSource: withdrawTransferValues (row 3): Connection refused: connect"
                   type="Failure">com.parasoft.api.tool.CustomToolException: Connection refused: connect&#xD;
	at StartCoverageTest.execute(StartCoverageTest.java:51)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:267)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:1)&#xD;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)&#xD;
	at java.base/java.lang.Thread.run(Thread.java:829)&#xD;
</failure>
      </testcase>
      <testcase name="Test Suite: Retrieve Accounts and Validate/Scenario: Withdrawl and Transfer/Test 2: login[withdrawTransferValues (row 1)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.044"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: withdrawTransferValues (row 1): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: withdrawTransferValues (row 1): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Retrieve Accounts and Validate/Scenario: Withdrawl and Transfer/Test 2: login[withdrawTransferValues (row 2)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.047"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: withdrawTransferValues (row 2): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: withdrawTransferValues (row 2): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Retrieve Accounts and Validate/Scenario: Withdrawl and Transfer/Test 2: login[withdrawTransferValues (row 3)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.026"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: withdrawTransferValues (row 3): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: withdrawTransferValues (row 3): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Retrieve Accounts and Validate/Scenario: Withdrawl and Transfer/Test 3: getAccounts[withdrawTransferValues (row 1)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.068"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: withdrawTransferValues (row 1): [customerId] No Data Source column named Test 1: id[1]
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

DataSource: withdrawTransferValues (row 1): No Data Source column named Test 1: id[1]
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

DataSource: withdrawTransferValues (row 1): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: withdrawTransferValues (row 1): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Retrieve Accounts and Validate/Scenario: Withdrawl and Transfer/Test 3: getAccounts[withdrawTransferValues (row 2)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.045"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: withdrawTransferValues (row 2): [customerId] No Data Source column named Test 1: id[1]
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

DataSource: withdrawTransferValues (row 2): No Data Source column named Test 1: id[1]
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

DataSource: withdrawTransferValues (row 2): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: withdrawTransferValues (row 2): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Retrieve Accounts and Validate/Scenario: Withdrawl and Transfer/Test 3: getAccounts[withdrawTransferValues (row 3)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.039"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: withdrawTransferValues (row 3): [customerId] No Data Source column named Test 1: id[1]
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

DataSource: withdrawTransferValues (row 3): No Data Source column named Test 1: id[1]
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

DataSource: withdrawTransferValues (row 3): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: withdrawTransferValues (row 3): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Retrieve Accounts and Validate/Scenario: Withdrawl and Transfer/Test 4: withdraw[withdrawTransferValues (row 1)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.070"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: withdrawTransferValues (row 1): Invalid WSDL. Connection refused: connect

DataSource: withdrawTransferValues (row 1): [accountId] No Data Source column named Test 3: id[1] 2
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

DataSource: withdrawTransferValues (row 1): No Data Source column named Test 3: id[1] 2
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

DataSource: withdrawTransferValues (row 1): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.</failure>
      </testcase>
      <testcase name="Test Suite: Retrieve Accounts and Validate/Scenario: Withdrawl and Transfer/Test 4: withdraw[withdrawTransferValues (row 2)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.041"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: withdrawTransferValues (row 2): Invalid WSDL. Connection refused: connect

DataSource: withdrawTransferValues (row 2): [accountId] No Data Source column named Test 3: id[1] 2
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

DataSource: withdrawTransferValues (row 2): No Data Source column named Test 3: id[1] 2
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

DataSource: withdrawTransferValues (row 2): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.</failure>
      </testcase>
      <testcase name="Test Suite: Retrieve Accounts and Validate/Scenario: Withdrawl and Transfer/Test 4: withdraw[withdrawTransferValues (row 3)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.032"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: withdrawTransferValues (row 3): Invalid WSDL. Connection refused: connect

DataSource: withdrawTransferValues (row 3): [accountId] No Data Source column named Test 3: id[1] 2
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

DataSource: withdrawTransferValues (row 3): No Data Source column named Test 3: id[1] 2
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

DataSource: withdrawTransferValues (row 3): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.</failure>
      </testcase>
      <testcase name="Test Suite: Retrieve Accounts and Validate/Scenario: Withdrawl and Transfer/Test 5: transfer[withdrawTransferValues (row 1)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.078"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: withdrawTransferValues (row 1): Invalid WSDL. Connection refused: connect

DataSource: withdrawTransferValues (row 1): [fromAccountId] No Data Source column named Test 3: id[1] 2
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

DataSource: withdrawTransferValues (row 1): No Data Source column named Test 3: id[1] 2
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

DataSource: withdrawTransferValues (row 1): [toAccountId] No Data Source column named Test 3: id[1] 3
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

DataSource: withdrawTransferValues (row 1): No Data Source column named Test 3: id[1] 3
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

DataSource: withdrawTransferValues (row 1): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.</failure>
      </testcase>
      <testcase name="Test Suite: Retrieve Accounts and Validate/Scenario: Withdrawl and Transfer/Test 5: transfer[withdrawTransferValues (row 2)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.055"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: withdrawTransferValues (row 2): Invalid WSDL. Connection refused: connect

DataSource: withdrawTransferValues (row 2): [fromAccountId] No Data Source column named Test 3: id[1] 2
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

DataSource: withdrawTransferValues (row 2): No Data Source column named Test 3: id[1] 2
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

DataSource: withdrawTransferValues (row 2): [toAccountId] No Data Source column named Test 3: id[1] 3
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

DataSource: withdrawTransferValues (row 2): No Data Source column named Test 3: id[1] 3
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

DataSource: withdrawTransferValues (row 2): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.</failure>
      </testcase>
      <testcase name="Test Suite: Retrieve Accounts and Validate/Scenario: Withdrawl and Transfer/Test 5: transfer[withdrawTransferValues (row 3)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.044"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: withdrawTransferValues (row 3): Invalid WSDL. Connection refused: connect

DataSource: withdrawTransferValues (row 3): [fromAccountId] No Data Source column named Test 3: id[1] 2
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

DataSource: withdrawTransferValues (row 3): No Data Source column named Test 3: id[1] 2
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

DataSource: withdrawTransferValues (row 3): [toAccountId] No Data Source column named Test 3: id[1] 3
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

DataSource: withdrawTransferValues (row 3): No Data Source column named Test 3: id[1] 3
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

DataSource: withdrawTransferValues (row 3): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.</failure>
      </testcase>
      <testcase name="Test Suite: Retrieve Accounts and Validate/Scenario: Withdrawl and Transfer/Test 6: getAccounts 2[withdrawTransferValues (row 1)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.045"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: withdrawTransferValues (row 1): [customerId] No Data Source column named Test 1: id[1]
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

DataSource: withdrawTransferValues (row 1): No Data Source column named Test 1: id[1]
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

DataSource: withdrawTransferValues (row 1): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: withdrawTransferValues (row 1): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Retrieve Accounts and Validate/Scenario: Withdrawl and Transfer/Test 6: getAccounts 2[withdrawTransferValues (row 2)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.045"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: withdrawTransferValues (row 2): [customerId] No Data Source column named Test 1: id[1]
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

DataSource: withdrawTransferValues (row 2): No Data Source column named Test 1: id[1]
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

DataSource: withdrawTransferValues (row 2): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: withdrawTransferValues (row 2): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Retrieve Accounts and Validate/Scenario: Withdrawl and Transfer/Test 6: getAccounts 2[withdrawTransferValues (row 3)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.050"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: withdrawTransferValues (row 3): [customerId] No Data Source column named Test 1: id[1]
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

DataSource: withdrawTransferValues (row 3): No Data Source column named Test 1: id[1]
This error often occurs when a column in the data source is renamed or removed.  This error can also occur when a column that is extracted via various Data Bank tools (e.g., XML Data Bank, Browser Data Bank) is renamed or removed.  Please verify whether the column still exists in the data source or the Data Bank tool.  When there are multiple data sources in the test suite, verify the data source specified in the Data Source drop down box in the upper right hand corner of the UI.  If the column has been renamed or removed, please select a new column in the UI.

If the column is extracted via a Data Bank tool, also verify whether the Data Bank tool was executed and whether the Data Bank tool received the input that it expected.

DataSource: withdrawTransferValues (row 3): Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.

DataSource: withdrawTransferValues (row 3): Invalid WSDL. Connection refused: connect</failure>
      </testcase>
      <testcase name="Test Suite: Retrieve Accounts and Validate/Tear-Down Tests/Tear-Down 1: Stop Coverage Session 2"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.017"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Connection refused: connect" type="Failure">com.parasoft.api.tool.CustomToolException: Connection refused: connect&#xD;
	at StopCoverageSession.execute(StopCoverageSession.java:51)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:267)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:1)&#xD;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)&#xD;
	at java.base/java.lang.Thread.run(Thread.java:829)&#xD;
Caused by: java.net.ConnectException: Connection refused: connect&#xD;
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)&#xD;
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:615)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:563)&#xD;
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:509)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:604)&#xD;
	at java.base/sun.net.www.http.HttpClient.&lt;init&gt;(HttpClient.java:277)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:376)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:397)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1258)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1192)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1086)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1020)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1597)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1525)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderFields(HttpURLConnection.java:3156)&#xD;
	at CoverageAgentController.getResponse(CoverageAgentController.java:238)&#xD;
	at CoverageAgentController.execute(CoverageAgentController.java:88)&#xD;
	at StopCoverageSession.execute(StopCoverageSession.java:47)&#xD;
	... 6 more&#xD;
[Nested Exception] java.net.ConnectException: Connection refused: connect&#xD;
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)&#xD;
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:615)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:563)&#xD;
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:509)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:604)&#xD;
	at java.base/sun.net.www.http.HttpClient.&lt;init&gt;(HttpClient.java:277)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:376)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:397)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1258)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1192)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1086)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1020)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1597)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1525)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderFields(HttpURLConnection.java:3156)&#xD;
	at CoverageAgentController.getResponse(CoverageAgentController.java:238)&#xD;
	at CoverageAgentController.execute(CoverageAgentController.java:88)&#xD;
	at StopCoverageSession.execute(StopCoverageSession.java:47)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:267)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:1)&#xD;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)&#xD;
	at java.base/java.lang.Thread.run(Thread.java:829)&#xD;
</failure>
      </testcase>
      <system-out/>
      <system-err/>
   </testsuite>
   <testsuite name="TestAssets.PB-WebUI-v3_tst"
               tests="5"
               id="2"
               package=""
               time="0.117"
               hostname="CD-LYAO-02"
               timestamp="2024-04-11T14:24:14"
               failures="5"
               errors="0">
      <properties/>
      <testcase name="Test Suite: Test Suite/Set-Up Tests/Set-Up 1: cleanDB"
                 classname="TestAssets.PB-WebUI-v3_tst"
                 time="0.028"
                 file="./soatest/TestAssets/PB-WebUI-v3.tst">
         <failure message="Multiple errors reported" type="Failure">Invalid WSDL. Connection refused: connect

Connection refused: connect
A connection error has been detected.  This may occur if a test has timed out while the client was still attempting to send or receive data.</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Set-Up Tests/Set-Up 2: Stop Coverage Session"
                 classname="TestAssets.PB-WebUI-v3_tst"
                 time="0.019"
                 file="./soatest/TestAssets/PB-WebUI-v3.tst">
         <failure message="Connection refused: connect" type="Failure">com.parasoft.api.tool.CustomToolException: Connection refused: connect&#xD;
	at StopCoverageSession.execute(StopCoverageSession.java:51)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:267)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:1)&#xD;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)&#xD;
	at java.base/java.lang.Thread.run(Thread.java:829)&#xD;
Caused by: java.net.ConnectException: Connection refused: connect&#xD;
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)&#xD;
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:615)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:563)&#xD;
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:509)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:604)&#xD;
	at java.base/sun.net.www.http.HttpClient.&lt;init&gt;(HttpClient.java:277)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:376)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:397)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1258)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1192)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1086)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1020)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1597)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1525)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderFields(HttpURLConnection.java:3156)&#xD;
	at CoverageAgentController.getResponse(CoverageAgentController.java:238)&#xD;
	at CoverageAgentController.execute(CoverageAgentController.java:88)&#xD;
	at StopCoverageSession.execute(StopCoverageSession.java:47)&#xD;
	... 6 more&#xD;
[Nested Exception] java.net.ConnectException: Connection refused: connect&#xD;
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)&#xD;
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:615)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:563)&#xD;
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:509)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:604)&#xD;
	at java.base/sun.net.www.http.HttpClient.&lt;init&gt;(HttpClient.java:277)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:376)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:397)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1258)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1192)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1086)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1020)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1597)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1525)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderFields(HttpURLConnection.java:3156)&#xD;
	at CoverageAgentController.getResponse(CoverageAgentController.java:238)&#xD;
	at CoverageAgentController.execute(CoverageAgentController.java:88)&#xD;
	at StopCoverageSession.execute(StopCoverageSession.java:47)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:267)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:1)&#xD;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)&#xD;
	at java.base/java.lang.Thread.run(Thread.java:829)&#xD;
</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Set-Up Tests/Set-Up 3: Start Coverage Session"
                 classname="TestAssets.PB-WebUI-v3_tst"
                 time="0.017"
                 file="./soatest/TestAssets/PB-WebUI-v3.tst">
         <failure message="Connection refused: connect" type="Failure">com.parasoft.api.tool.CustomToolException: Connection refused: connect&#xD;
	at StartCoverageSession.execute(StartCoverageSession.java:51)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:267)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:1)&#xD;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)&#xD;
	at java.base/java.lang.Thread.run(Thread.java:829)&#xD;
Caused by: java.net.ConnectException: Connection refused: connect&#xD;
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)&#xD;
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:615)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:563)&#xD;
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:509)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:604)&#xD;
	at java.base/sun.net.www.http.HttpClient.&lt;init&gt;(HttpClient.java:277)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:376)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:397)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1258)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1192)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1086)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1020)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1597)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1525)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderFields(HttpURLConnection.java:3156)&#xD;
	at CoverageAgentController.getResponse(CoverageAgentController.java:238)&#xD;
	at CoverageAgentController.execute(CoverageAgentController.java:88)&#xD;
	at StartCoverageSession.execute(StartCoverageSession.java:47)&#xD;
	... 6 more&#xD;
[Nested Exception] java.net.ConnectException: Connection refused: connect&#xD;
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)&#xD;
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:615)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:563)&#xD;
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:509)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:604)&#xD;
	at java.base/sun.net.www.http.HttpClient.&lt;init&gt;(HttpClient.java:277)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:376)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:397)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1258)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1192)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1086)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1020)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1597)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1525)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderFields(HttpURLConnection.java:3156)&#xD;
	at CoverageAgentController.getResponse(CoverageAgentController.java:238)&#xD;
	at CoverageAgentController.execute(CoverageAgentController.java:88)&#xD;
	at StartCoverageSession.execute(StartCoverageSession.java:47)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:267)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:1)&#xD;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)&#xD;
	at java.base/java.lang.Thread.run(Thread.java:829)&#xD;
</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: Web Scenarios/Scenario: Basic UX Workflow/Test 1: Start Coverage Test: Web UI/UX"
                 classname="TestAssets.PB-WebUI-v3_tst"
                 time="0.025"
                 file="./soatest/TestAssets/PB-WebUI-v3.tst">
         <failure message="Connection refused: connect" type="Failure">com.parasoft.api.tool.CustomToolException: Connection refused: connect&#xD;
	at StartCoverageTest.execute(StartCoverageTest.java:51)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:267)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:1)&#xD;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)&#xD;
	at java.base/java.lang.Thread.run(Thread.java:829)&#xD;
</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Tear-Down Tests/Tear-Down 1: Stop Coverage Session 2"
                 classname="TestAssets.PB-WebUI-v3_tst"
                 time="0.028"
                 file="./soatest/TestAssets/PB-WebUI-v3.tst">
         <failure message="Connection refused: connect" type="Failure">com.parasoft.api.tool.CustomToolException: Connection refused: connect&#xD;
	at StopCoverageSession.execute(StopCoverageSession.java:51)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:267)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:1)&#xD;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)&#xD;
	at java.base/java.lang.Thread.run(Thread.java:829)&#xD;
Caused by: java.net.ConnectException: Connection refused: connect&#xD;
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)&#xD;
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:615)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:563)&#xD;
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:509)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:604)&#xD;
	at java.base/sun.net.www.http.HttpClient.&lt;init&gt;(HttpClient.java:277)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:376)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:397)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1258)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1192)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1086)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1020)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1597)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1525)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderFields(HttpURLConnection.java:3156)&#xD;
	at CoverageAgentController.getResponse(CoverageAgentController.java:238)&#xD;
	at CoverageAgentController.execute(CoverageAgentController.java:88)&#xD;
	at StopCoverageSession.execute(StopCoverageSession.java:47)&#xD;
	... 6 more&#xD;
[Nested Exception] java.net.ConnectException: Connection refused: connect&#xD;
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)&#xD;
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:615)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:563)&#xD;
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:509)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:604)&#xD;
	at java.base/sun.net.www.http.HttpClient.&lt;init&gt;(HttpClient.java:277)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:376)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:397)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1258)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1192)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1086)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1020)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1597)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1525)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderFields(HttpURLConnection.java:3156)&#xD;
	at CoverageAgentController.getResponse(CoverageAgentController.java:238)&#xD;
	at CoverageAgentController.execute(CoverageAgentController.java:88)&#xD;
	at StopCoverageSession.execute(StopCoverageSession.java:47)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:267)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:1)&#xD;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)&#xD;
	at java.base/java.lang.Thread.run(Thread.java:829)&#xD;
</failure>
      </testcase>
      <system-out/>
      <system-err/>
   </testsuite>
   <testsuite name="TestAssets.Smoke_tst"
               tests="51"
               id="3"
               package=""
               time="11.714"
               hostname="CD-LYAO-02"
               timestamp="2024-04-11T14:24:14"
               failures="2"
               errors="0">
      <properties/>
      <testcase name="Test Suite: Test Suite/Test Suite: Initialize ParaBank/Test 1: Login to initialize"
                 classname="TestAssets.Smoke_tst"
                 time="0.148"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore/Test 1: Check BookStore WSDL"
                 classname="TestAssets.Smoke_tst"
                 time="0.877"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore/Test 2: getItemById"
                 classname="TestAssets.Smoke_tst"
                 time="0.364"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore/Test 3: getItemByTitle"
                 classname="TestAssets.Smoke_tst"
                 time="0.067"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Username Token/Test Suite: SearchBooks/Test 1: getItemByTitle(string)[Auth Data (row 1)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.163"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Username Token/Test Suite: SearchBooks/Test 1: getItemByTitle(string)[Auth Data (row 2)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.097"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Username Token/Test Suite: SearchBooks/Test 1: getItemByTitle(string)[Auth Data (row 3)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.033"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Username Token/Test Suite: SearchBooks/Test 1: getItemByTitle(string)[Auth Data (row 4)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.037"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Username Token/Test Suite: SearchBooks/Test 1: getItemByTitle(string)[Auth Data (row 5)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.045"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Username Token/Test Suite: SearchBooks/Test 1: getItemByTitle(string)[Auth Data (row 6)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.037"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Username Token/Test Suite: SearchBooks/Test 1: getItemByTitle(string)[Auth Data (row 7)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.038"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Username Token/Test Suite: SearchBooks/Test 2: getItemById(int)"
                 classname="TestAssets.Smoke_tst"
                 time="0.068"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Signature/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 1)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.691"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Signature/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 2)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.104"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Signature/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 3)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.098"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Signature/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 4)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.089"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Signature/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 5)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.102"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Signature/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 6)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.106"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Signature/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 7)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.096"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Signature/Test 2: getItemsInCart"
                 classname="TestAssets.Smoke_tst"
                 time="0.156"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Signature/Test 3: submitOrder"
                 classname="TestAssets.Smoke_tst"
                 time="0.107"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 1)]"
                 classname="TestAssets.Smoke_tst"
                 time="1.307"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 2)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.117"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 3)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.093"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 4)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.095"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 5)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.096"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 6)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.087"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 7)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.078"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption/Test 2: getItemsInCart"
                 classname="TestAssets.Smoke_tst"
                 time="0.118"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption/Test 3: submitOrder"
                 classname="TestAssets.Smoke_tst"
                 time="0.109"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption and Signature/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 1)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.232"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption and Signature/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 2)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.157"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption and Signature/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 3)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.153"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption and Signature/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 4)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.153"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption and Signature/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 5)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.150"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption and Signature/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 6)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.187"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption and Signature/Scenario: OrderMultiple/Test 1: addItemToCart[Orders by IDs (row 7)]"
                 classname="TestAssets.Smoke_tst"
                 time="0.156"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption and Signature/Test 2: getItemsInCart"
                 classname="TestAssets.Smoke_tst"
                 time="0.198"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: BookStore - WS-Security/Test Suite: Encryption and Signature/Test 3: submitOrder"
                 classname="TestAssets.Smoke_tst"
                 time="0.182"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: ParaBank/Test 1: Check ParaBank WSDL"
                 classname="TestAssets.Smoke_tst"
                 time="0.348"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: ParaBank/Test 2: getAccount"
                 classname="TestAssets.Smoke_tst"
                 time="0.175"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: ParaBank/Test 3: getCustomer"
                 classname="TestAssets.Smoke_tst"
                 time="0.088"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: LoanProcessor/Test 1: Check LoanProcessor WSDL"
                 classname="TestAssets.Smoke_tst"
                 time="0.051"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: SOAP/Test Suite: LoanProcessor/Test 2: requestLoan"
                 classname="TestAssets.Smoke_tst"
                 time="0.095"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: REST/Test Suite: ParaBank/Test 1: Check OpenAPI"
                 classname="TestAssets.Smoke_tst"
                 time="0.253"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: REST/Test Suite: ParaBank/Test Suite: /accounts/{accountId}/Test 1: /accounts/{accountId} - GET"
                 classname="TestAssets.Smoke_tst"
                 time="1.462"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: REST/Test Suite: ParaBank/Test Suite: /customers/{customerId}/Test 1: /customers/{customerId} - GET"
                 classname="TestAssets.Smoke_tst"
                 time="0.022"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: Web/Test 1: Front Page"
                 classname="TestAssets.Smoke_tst"
                 time="0.935"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: JMS/Test Suite: LoanProcessor/Test 1: Request Loan JMS"
                 classname="TestAssets.Smoke_tst"
                 time="0.839"
                 file="./soatest/TestAssets/Smoke.tst"/>
      <testcase name="Test Suite: Test Suite/Test Suite: DB/Test Suite: BookStore/Test 1: Books"
                 classname="TestAssets.Smoke_tst"
                 time="0.205"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">Changed element name from the expected "resultSet" to "SQLException" in XPath /results/resultSet
Expected element tag name 'resultSet' but was 'SQLException' - comparing &lt;resultSet...&gt; at /results[1]/resultSet[1] to &lt;SQLException...&gt; at /results[1]/SQLException[1]
Source: text

Changed element type from "Element" to "Text" in XPath /results/resultSet/rows
Expected node type '1' but was '3' - comparing &lt;rows...&gt; at /results[1]/resultSet[1]/rows[1] to &lt;SQLException ...&gt;java.sql.SQLException: Unable to instantiate class "org.hsqldb.jdbcDriver". Please check the DB driver classname and the jar file locations in Parasoft &gt; Preferences &gt; JDBC Drivers.&lt;/SQLException&gt; at /results[1]/SQLException[1]/text()[1]
Source: text

Deleted element at XPath /results/resultSet/rows/row[1]
Expected presence of child node 'row' but was 'null' - comparing &lt;row...&gt; at /results[1]/resultSet[1]/rows[1]/row[1] to  at null
Source: text

Deleted element at XPath /results/resultSet/rows/row[2]
Expected presence of child node 'row' but was 'null' - comparing &lt;row...&gt; at /results[1]/resultSet[1]/rows[1]/row[2] to  at null
Source: text

Deleted element at XPath /results/resultSet/rows/row[3]
Expected presence of child node 'row' but was 'null' - comparing &lt;row...&gt; at /results[1]/resultSet[1]/rows[1]/row[3] to  at null
Source: text

Deleted element at XPath /results/resultSet/rows/row[4]
Expected presence of child node 'row' but was 'null' - comparing &lt;row...&gt; at /results[1]/resultSet[1]/rows[1]/row[4] to  at null
Source: text

Deleted element at XPath /results/resultSet/rows/row[5]
Expected presence of child node 'row' but was 'null' - comparing &lt;row...&gt; at /results[1]/resultSet[1]/rows[1]/row[5] to  at null
Source: text

Deleted element at XPath /results/resultSet/rows/row[6]
Expected presence of child node 'row' but was 'null' - comparing &lt;row...&gt; at /results[1]/resultSet[1]/rows[1]/row[6] to  at null
Source: text

Deleted element at XPath /results/resultSet/rows/row[7]
Expected presence of child node 'row' but was 'null' - comparing &lt;row...&gt; at /results[1]/resultSet[1]/rows[1]/row[7] to  at null
Source: text

Deleted element at XPath /results/resultSet/rows/row[8]
Expected presence of child node 'row' but was 'null' - comparing &lt;row...&gt; at /results[1]/resultSet[1]/rows[1]/row[8] to  at null
Source: text

Deleted element at XPath /results/resultSet/rows/row[9]
Expected presence of child node 'row' but was 'null' - comparing &lt;row...&gt; at /results[1]/resultSet[1]/rows[1]/row[9] to  at null
Source: text</failure>
      </testcase>
      <testcase name="Test Suite: Test Suite/Test Suite: DB/Test Suite: ParaBank/Test 1: Customers"
                 classname="TestAssets.Smoke_tst"
                 time="0.050"
                 file="./soatest/TestAssets/Smoke.tst">
         <failure message="Multiple errors reported" type="Failure">Changed element name from the expected "resultSet" to "SQLException" in XPath /results/resultSet
Expected element tag name 'resultSet' but was 'SQLException' - comparing &lt;resultSet...&gt; at /results[1]/resultSet[1] to &lt;SQLException...&gt; at /results[1]/SQLException[1]
Source: text

Changed element type from "Element" to "Text" in XPath /results/resultSet/rows
Expected node type '1' but was '3' - comparing &lt;rows...&gt; at /results[1]/resultSet[1]/rows[1] to &lt;SQLException ...&gt;java.sql.SQLException: Unable to instantiate class "org.hsqldb.jdbcDriver". Please check the DB driver classname and the jar file locations in Parasoft &gt; Preferences &gt; JDBC Drivers.&lt;/SQLException&gt; at /results[1]/SQLException[1]/text()[1]
Source: text

Deleted element at XPath /results/resultSet/rows/row[1]
Expected presence of child node 'row' but was 'null' - comparing &lt;row...&gt; at /results[1]/resultSet[1]/rows[1]/row[1] to  at null
Source: text

Deleted element at XPath /results/resultSet/rows/row[2]
Expected presence of child node 'row' but was 'null' - comparing &lt;row...&gt; at /results[1]/resultSet[1]/rows[1]/row[2] to  at null
Source: text</failure>
      </testcase>
      <system-out/>
      <system-err/>
   </testsuite>
</testsuites>
