<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
   <testsuite name="TestAssets.PB-ParabankServices-v3_tst"
               tests="30"
               id="1"
               package=""
               time="0.810"
               hostname="CD-LYAO-02"
               timestamp="2024-04-11T12:02:35"
               failures="30"
               errors="0">
      <properties/>
      <testcase name="测试套件: Retrieve Accounts and Validate/设置测试/设置 1: cleanDB"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.184"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">无效的 WSDL。 Connection refused: connect

Connection refused: connect
检测到一个连接错误。如果一个测试已经超时而客户端仍然在试图发送或者接受数据，则可能会发生这样一个错误。</failure>
      </testcase>
      <testcase name="测试套件: Retrieve Accounts and Validate/设置测试/设置 2: Stop Coverage Session"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.013"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Connection refused: connect" type="Failure">com.parasoft.api.tool.CustomToolException: Connection refused: connect&#xD;
	at StopCoverageSession.execute(StopCoverageSession.java:51)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:267)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:1)&#xD;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)&#xD;
	at java.base/java.lang.Thread.run(Thread.java:829)&#xD;
Caused by: java.net.ConnectException: Connection refused: connect&#xD;
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)&#xD;
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:615)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:563)&#xD;
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:509)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:604)&#xD;
	at java.base/sun.net.www.http.HttpClient.&lt;init&gt;(HttpClient.java:277)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:376)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:397)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1258)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1192)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1086)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1020)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1597)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1525)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderFields(HttpURLConnection.java:3156)&#xD;
	at CoverageAgentController.getResponse(CoverageAgentController.java:238)&#xD;
	at CoverageAgentController.execute(CoverageAgentController.java:88)&#xD;
	at StopCoverageSession.execute(StopCoverageSession.java:47)&#xD;
	... 6 more&#xD;
[嵌套表达式] java.net.ConnectException: Connection refused: connect&#xD;
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)&#xD;
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:615)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:563)&#xD;
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:509)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:604)&#xD;
	at java.base/sun.net.www.http.HttpClient.&lt;init&gt;(HttpClient.java:277)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:376)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:397)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1258)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1192)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1086)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1020)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1597)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1525)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderFields(HttpURLConnection.java:3156)&#xD;
	at CoverageAgentController.getResponse(CoverageAgentController.java:238)&#xD;
	at CoverageAgentController.execute(CoverageAgentController.java:88)&#xD;
	at StopCoverageSession.execute(StopCoverageSession.java:47)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:267)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:1)&#xD;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)&#xD;
	at java.base/java.lang.Thread.run(Thread.java:829)&#xD;
</failure>
      </testcase>
      <testcase name="测试套件: Retrieve Accounts and Validate/设置测试/设置 3: Start Coverage Session"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.006"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Connection refused: connect" type="Failure">com.parasoft.api.tool.CustomToolException: Connection refused: connect&#xD;
	at StartCoverageSession.execute(StartCoverageSession.java:51)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:267)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:1)&#xD;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)&#xD;
	at java.base/java.lang.Thread.run(Thread.java:829)&#xD;
Caused by: java.net.ConnectException: Connection refused: connect&#xD;
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)&#xD;
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:615)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:563)&#xD;
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:509)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:604)&#xD;
	at java.base/sun.net.www.http.HttpClient.&lt;init&gt;(HttpClient.java:277)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:376)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:397)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1258)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1192)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1086)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1020)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1597)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1525)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderFields(HttpURLConnection.java:3156)&#xD;
	at CoverageAgentController.getResponse(CoverageAgentController.java:238)&#xD;
	at CoverageAgentController.execute(CoverageAgentController.java:88)&#xD;
	at StartCoverageSession.execute(StartCoverageSession.java:47)&#xD;
	... 6 more&#xD;
[嵌套表达式] java.net.ConnectException: Connection refused: connect&#xD;
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)&#xD;
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:615)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:563)&#xD;
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:509)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:604)&#xD;
	at java.base/sun.net.www.http.HttpClient.&lt;init&gt;(HttpClient.java:277)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:376)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:397)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1258)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1192)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1086)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1020)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1597)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1525)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderFields(HttpURLConnection.java:3156)&#xD;
	at CoverageAgentController.getResponse(CoverageAgentController.java:238)&#xD;
	at CoverageAgentController.execute(CoverageAgentController.java:88)&#xD;
	at StartCoverageSession.execute(StartCoverageSession.java:47)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:267)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:1)&#xD;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)&#xD;
	at java.base/java.lang.Thread.run(Thread.java:829)&#xD;
</failure>
      </testcase>
      <testcase name="测试套件: Retrieve Accounts and Validate/场景: Get Accounts/测试 1: Start Coverage Test: Get Accounts"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.006"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Connection refused: connect" type="Failure">com.parasoft.api.tool.CustomToolException: Connection refused: connect&#xD;
	at StartCoverageTest.execute(StartCoverageTest.java:51)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:267)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:1)&#xD;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)&#xD;
	at java.base/java.lang.Thread.run(Thread.java:829)&#xD;
</failure>
      </testcase>
      <testcase name="测试套件: Retrieve Accounts and Validate/场景: Get Accounts/测试 2: login"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.034"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">Connection refused: connect
检测到一个连接错误。如果一个测试已经超时而客户端仍然在试图发送或者接受数据，则可能会发生这样一个错误。

无效的 WSDL。 Connection refused: connect</failure>
      </testcase>
      <testcase name="测试套件: Retrieve Accounts and Validate/场景: Get Accounts/测试 3: getAccounts"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.032"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">[customerId] 没有名为Test 1: id[1]的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

没有名为Test 1: id[1]的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

Connection refused: connect
检测到一个连接错误。如果一个测试已经超时而客户端仍然在试图发送或者接受数据，则可能会发生这样一个错误。

无效的 WSDL。 Connection refused: connect</failure>
      </testcase>
      <testcase name="测试套件: Retrieve Accounts and Validate/场景: Open Account/测试 1: Start Coverage Test: Open Account"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.008"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Connection refused: connect" type="Failure">com.parasoft.api.tool.CustomToolException: Connection refused: connect&#xD;
	at StartCoverageTest.execute(StartCoverageTest.java:51)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:267)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:1)&#xD;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)&#xD;
	at java.base/java.lang.Thread.run(Thread.java:829)&#xD;
</failure>
      </testcase>
      <testcase name="测试套件: Retrieve Accounts and Validate/场景: Open Account/测试 2: login"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.012"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">Connection refused: connect
检测到一个连接错误。如果一个测试已经超时而客户端仍然在试图发送或者接受数据，则可能会发生这样一个错误。

无效的 WSDL。 Connection refused: connect</failure>
      </testcase>
      <testcase name="测试套件: Retrieve Accounts and Validate/场景: Open Account/测试 3: getAccounts"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.038"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">[customerId] 没有名为Test 1: id[1]的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

没有名为Test 1: id[1]的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

Connection refused: connect
检测到一个连接错误。如果一个测试已经超时而客户端仍然在试图发送或者接受数据，则可能会发生这样一个错误。

无效的 WSDL。 Connection refused: connect</failure>
      </testcase>
      <testcase name="测试套件: Retrieve Accounts and Validate/场景: Open Account/测试 4: createAccount"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.034"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">无效的 WSDL。 Connection refused: connect

[customerId] 没有名为Test 1: id[1]的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

没有名为Test 1: id[1]的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

[fromAccountId] 没有名为Test 3: id[1]的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

没有名为Test 3: id[1]的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

Connection refused: connect
检测到一个连接错误。如果一个测试已经超时而客户端仍然在试图发送或者接受数据，则可能会发生这样一个错误。</failure>
      </testcase>
      <testcase name="测试套件: Retrieve Accounts and Validate/场景: Open Account/测试 5: getAccounts 2"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.028"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">[customerId] 没有名为Test 1: id[1]的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

没有名为Test 1: id[1]的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

Connection refused: connect
检测到一个连接错误。如果一个测试已经超时而客户端仍然在试图发送或者接受数据，则可能会发生这样一个错误。

无效的 WSDL。 Connection refused: connect</failure>
      </testcase>
      <testcase name="测试套件: Retrieve Accounts and Validate/场景: Withdrawl and Transfer/测试 1: Start Coverage Test: Withdrawl and Transfer[withdrawTransferValues (行 1)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.008"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="DataSource: withdrawTransferValues (行 1): Connection refused: connect"
                   type="Failure">com.parasoft.api.tool.CustomToolException: Connection refused: connect&#xD;
	at StartCoverageTest.execute(StartCoverageTest.java:51)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:267)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:1)&#xD;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)&#xD;
	at java.base/java.lang.Thread.run(Thread.java:829)&#xD;
</failure>
      </testcase>
      <testcase name="测试套件: Retrieve Accounts and Validate/场景: Withdrawl and Transfer/测试 1: Start Coverage Test: Withdrawl and Transfer[withdrawTransferValues (行 2)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.005"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="DataSource: withdrawTransferValues (行 2): Connection refused: connect"
                   type="Failure">com.parasoft.api.tool.CustomToolException: Connection refused: connect&#xD;
	at StartCoverageTest.execute(StartCoverageTest.java:51)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:267)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:1)&#xD;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)&#xD;
	at java.base/java.lang.Thread.run(Thread.java:829)&#xD;
</failure>
      </testcase>
      <testcase name="测试套件: Retrieve Accounts and Validate/场景: Withdrawl and Transfer/测试 1: Start Coverage Test: Withdrawl and Transfer[withdrawTransferValues (行 3)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.006"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="DataSource: withdrawTransferValues (行 3): Connection refused: connect"
                   type="Failure">com.parasoft.api.tool.CustomToolException: Connection refused: connect&#xD;
	at StartCoverageTest.execute(StartCoverageTest.java:51)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:267)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:1)&#xD;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)&#xD;
	at java.base/java.lang.Thread.run(Thread.java:829)&#xD;
</failure>
      </testcase>
      <testcase name="测试套件: Retrieve Accounts and Validate/场景: Withdrawl and Transfer/测试 2: login[withdrawTransferValues (行 1)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.031"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: withdrawTransferValues (行 1): Connection refused: connect
检测到一个连接错误。如果一个测试已经超时而客户端仍然在试图发送或者接受数据，则可能会发生这样一个错误。

DataSource: withdrawTransferValues (行 1): 无效的 WSDL。 Connection refused: connect</failure>
      </testcase>
      <testcase name="测试套件: Retrieve Accounts and Validate/场景: Withdrawl and Transfer/测试 2: login[withdrawTransferValues (行 2)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.021"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: withdrawTransferValues (行 2): Connection refused: connect
检测到一个连接错误。如果一个测试已经超时而客户端仍然在试图发送或者接受数据，则可能会发生这样一个错误。

DataSource: withdrawTransferValues (行 2): 无效的 WSDL。 Connection refused: connect</failure>
      </testcase>
      <testcase name="测试套件: Retrieve Accounts and Validate/场景: Withdrawl and Transfer/测试 2: login[withdrawTransferValues (行 3)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.023"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: withdrawTransferValues (行 3): Connection refused: connect
检测到一个连接错误。如果一个测试已经超时而客户端仍然在试图发送或者接受数据，则可能会发生这样一个错误。

DataSource: withdrawTransferValues (行 3): 无效的 WSDL。 Connection refused: connect</failure>
      </testcase>
      <testcase name="测试套件: Retrieve Accounts and Validate/场景: Withdrawl and Transfer/测试 3: getAccounts[withdrawTransferValues (行 1)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.011"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: withdrawTransferValues (行 1): [customerId] 没有名为Test 1: id[1]的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

DataSource: withdrawTransferValues (行 1): 没有名为Test 1: id[1]的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

DataSource: withdrawTransferValues (行 1): Connection refused: connect
检测到一个连接错误。如果一个测试已经超时而客户端仍然在试图发送或者接受数据，则可能会发生这样一个错误。

DataSource: withdrawTransferValues (行 1): 无效的 WSDL。 Connection refused: connect</failure>
      </testcase>
      <testcase name="测试套件: Retrieve Accounts and Validate/场景: Withdrawl and Transfer/测试 3: getAccounts[withdrawTransferValues (行 2)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.018"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: withdrawTransferValues (行 2): [customerId] 没有名为Test 1: id[1]的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

DataSource: withdrawTransferValues (行 2): 没有名为Test 1: id[1]的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

DataSource: withdrawTransferValues (行 2): Connection refused: connect
检测到一个连接错误。如果一个测试已经超时而客户端仍然在试图发送或者接受数据，则可能会发生这样一个错误。

DataSource: withdrawTransferValues (行 2): 无效的 WSDL。 Connection refused: connect</failure>
      </testcase>
      <testcase name="测试套件: Retrieve Accounts and Validate/场景: Withdrawl and Transfer/测试 3: getAccounts[withdrawTransferValues (行 3)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.033"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: withdrawTransferValues (行 3): [customerId] 没有名为Test 1: id[1]的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

DataSource: withdrawTransferValues (行 3): 没有名为Test 1: id[1]的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

DataSource: withdrawTransferValues (行 3): Connection refused: connect
检测到一个连接错误。如果一个测试已经超时而客户端仍然在试图发送或者接受数据，则可能会发生这样一个错误。

DataSource: withdrawTransferValues (行 3): 无效的 WSDL。 Connection refused: connect</failure>
      </testcase>
      <testcase name="测试套件: Retrieve Accounts and Validate/场景: Withdrawl and Transfer/测试 4: withdraw[withdrawTransferValues (行 1)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.038"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: withdrawTransferValues (行 1): 无效的 WSDL。 Connection refused: connect

DataSource: withdrawTransferValues (行 1): [accountId] 没有名为Test 3: id[1] 2的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

DataSource: withdrawTransferValues (行 1): 没有名为Test 3: id[1] 2的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

DataSource: withdrawTransferValues (行 1): Connection refused: connect
检测到一个连接错误。如果一个测试已经超时而客户端仍然在试图发送或者接受数据，则可能会发生这样一个错误。</failure>
      </testcase>
      <testcase name="测试套件: Retrieve Accounts and Validate/场景: Withdrawl and Transfer/测试 4: withdraw[withdrawTransferValues (行 2)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.029"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: withdrawTransferValues (行 2): 无效的 WSDL。 Connection refused: connect

DataSource: withdrawTransferValues (行 2): [accountId] 没有名为Test 3: id[1] 2的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

DataSource: withdrawTransferValues (行 2): 没有名为Test 3: id[1] 2的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

DataSource: withdrawTransferValues (行 2): Connection refused: connect
检测到一个连接错误。如果一个测试已经超时而客户端仍然在试图发送或者接受数据，则可能会发生这样一个错误。</failure>
      </testcase>
      <testcase name="测试套件: Retrieve Accounts and Validate/场景: Withdrawl and Transfer/测试 4: withdraw[withdrawTransferValues (行 3)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.030"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: withdrawTransferValues (行 3): 无效的 WSDL。 Connection refused: connect

DataSource: withdrawTransferValues (行 3): [accountId] 没有名为Test 3: id[1] 2的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

DataSource: withdrawTransferValues (行 3): 没有名为Test 3: id[1] 2的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

DataSource: withdrawTransferValues (行 3): Connection refused: connect
检测到一个连接错误。如果一个测试已经超时而客户端仍然在试图发送或者接受数据，则可能会发生这样一个错误。</failure>
      </testcase>
      <testcase name="测试套件: Retrieve Accounts and Validate/场景: Withdrawl and Transfer/测试 5: transfer[withdrawTransferValues (行 1)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.017"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: withdrawTransferValues (行 1): 无效的 WSDL。 Connection refused: connect

DataSource: withdrawTransferValues (行 1): [fromAccountId] 没有名为Test 3: id[1] 2的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

DataSource: withdrawTransferValues (行 1): 没有名为Test 3: id[1] 2的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

DataSource: withdrawTransferValues (行 1): [toAccountId] 没有名为Test 3: id[1] 3的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

DataSource: withdrawTransferValues (行 1): 没有名为Test 3: id[1] 3的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

DataSource: withdrawTransferValues (行 1): Connection refused: connect
检测到一个连接错误。如果一个测试已经超时而客户端仍然在试图发送或者接受数据，则可能会发生这样一个错误。</failure>
      </testcase>
      <testcase name="测试套件: Retrieve Accounts and Validate/场景: Withdrawl and Transfer/测试 5: transfer[withdrawTransferValues (行 2)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.017"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: withdrawTransferValues (行 2): 无效的 WSDL。 Connection refused: connect

DataSource: withdrawTransferValues (行 2): [fromAccountId] 没有名为Test 3: id[1] 2的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

DataSource: withdrawTransferValues (行 2): 没有名为Test 3: id[1] 2的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

DataSource: withdrawTransferValues (行 2): [toAccountId] 没有名为Test 3: id[1] 3的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

DataSource: withdrawTransferValues (行 2): 没有名为Test 3: id[1] 3的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

DataSource: withdrawTransferValues (行 2): Connection refused: connect
检测到一个连接错误。如果一个测试已经超时而客户端仍然在试图发送或者接受数据，则可能会发生这样一个错误。</failure>
      </testcase>
      <testcase name="测试套件: Retrieve Accounts and Validate/场景: Withdrawl and Transfer/测试 5: transfer[withdrawTransferValues (行 3)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.034"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: withdrawTransferValues (行 3): 无效的 WSDL。 Connection refused: connect

DataSource: withdrawTransferValues (行 3): [fromAccountId] 没有名为Test 3: id[1] 2的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

DataSource: withdrawTransferValues (行 3): 没有名为Test 3: id[1] 2的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

DataSource: withdrawTransferValues (行 3): [toAccountId] 没有名为Test 3: id[1] 3的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

DataSource: withdrawTransferValues (行 3): 没有名为Test 3: id[1] 3的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

DataSource: withdrawTransferValues (行 3): Connection refused: connect
检测到一个连接错误。如果一个测试已经超时而客户端仍然在试图发送或者接受数据，则可能会发生这样一个错误。</failure>
      </testcase>
      <testcase name="测试套件: Retrieve Accounts and Validate/场景: Withdrawl and Transfer/测试 6: getAccounts 2[withdrawTransferValues (行 1)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.029"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: withdrawTransferValues (行 1): [customerId] 没有名为Test 1: id[1]的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

DataSource: withdrawTransferValues (行 1): 没有名为Test 1: id[1]的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

DataSource: withdrawTransferValues (行 1): Connection refused: connect
检测到一个连接错误。如果一个测试已经超时而客户端仍然在试图发送或者接受数据，则可能会发生这样一个错误。

DataSource: withdrawTransferValues (行 1): 无效的 WSDL。 Connection refused: connect</failure>
      </testcase>
      <testcase name="测试套件: Retrieve Accounts and Validate/场景: Withdrawl and Transfer/测试 6: getAccounts 2[withdrawTransferValues (行 2)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.029"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: withdrawTransferValues (行 2): [customerId] 没有名为Test 1: id[1]的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

DataSource: withdrawTransferValues (行 2): 没有名为Test 1: id[1]的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

DataSource: withdrawTransferValues (行 2): Connection refused: connect
检测到一个连接错误。如果一个测试已经超时而客户端仍然在试图发送或者接受数据，则可能会发生这样一个错误。

DataSource: withdrawTransferValues (行 2): 无效的 WSDL。 Connection refused: connect</failure>
      </testcase>
      <testcase name="测试套件: Retrieve Accounts and Validate/场景: Withdrawl and Transfer/测试 6: getAccounts 2[withdrawTransferValues (行 3)]"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.031"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Multiple errors reported" type="Failure">DataSource: withdrawTransferValues (行 3): [customerId] 没有名为Test 1: id[1]的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

DataSource: withdrawTransferValues (行 3): 没有名为Test 1: id[1]的数据源列
此错误经常发生在重命名或移除数据源中的列的过程中.当从不同数据库工具中提取的列被重命名或移除时，也会出现该错误。(例如, XML数据库,浏览器数据库). 请核实列是否依然存在于数据源或数据库工具.当测试套件中有多个数据源, 请核实UI右上角的数据源下拉框中指定的数据源. 如果该列已经被重命名或移除,请选择UI中一个新的列.

如果一个列通过数据库工具被提取,也请检测数据库工具是否被执行，且数据库工具是否接收到期望的输入.

DataSource: withdrawTransferValues (行 3): Connection refused: connect
检测到一个连接错误。如果一个测试已经超时而客户端仍然在试图发送或者接受数据，则可能会发生这样一个错误。

DataSource: withdrawTransferValues (行 3): 无效的 WSDL。 Connection refused: connect</failure>
      </testcase>
      <testcase name="测试套件: Retrieve Accounts and Validate/拆除测试/拆除 1: Stop Coverage Session 2"
                 classname="TestAssets.PB-ParabankServices-v3_tst"
                 time="0.005"
                 file="./soatest/TestAssets/PB-ParabankServices-v3.tst">
         <failure message="Connection refused: connect" type="Failure">com.parasoft.api.tool.CustomToolException: Connection refused: connect&#xD;
	at StopCoverageSession.execute(StopCoverageSession.java:51)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:267)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:1)&#xD;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)&#xD;
	at java.base/java.lang.Thread.run(Thread.java:829)&#xD;
Caused by: java.net.ConnectException: Connection refused: connect&#xD;
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)&#xD;
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:615)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:563)&#xD;
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:509)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:604)&#xD;
	at java.base/sun.net.www.http.HttpClient.&lt;init&gt;(HttpClient.java:277)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:376)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:397)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1258)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1192)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1086)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1020)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1597)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1525)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderFields(HttpURLConnection.java:3156)&#xD;
	at CoverageAgentController.getResponse(CoverageAgentController.java:238)&#xD;
	at CoverageAgentController.execute(CoverageAgentController.java:88)&#xD;
	at StopCoverageSession.execute(StopCoverageSession.java:47)&#xD;
	... 6 more&#xD;
[嵌套表达式] java.net.ConnectException: Connection refused: connect&#xD;
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)&#xD;
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)&#xD;
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:615)&#xD;
	at java.base/java.net.Socket.connect(Socket.java:563)&#xD;
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:509)&#xD;
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:604)&#xD;
	at java.base/sun.net.www.http.HttpClient.&lt;init&gt;(HttpClient.java:277)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:376)&#xD;
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:397)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1258)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1192)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1086)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1020)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1597)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1525)&#xD;
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderFields(HttpURLConnection.java:3156)&#xD;
	at CoverageAgentController.getResponse(CoverageAgentController.java:238)&#xD;
	at CoverageAgentController.execute(CoverageAgentController.java:88)&#xD;
	at StopCoverageSession.execute(StopCoverageSession.java:47)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:267)&#xD;
	at webtool.extension.tool.CustomTool$ApplyTool.call(CustomTool.java:1)&#xD;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)&#xD;
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)&#xD;
	at java.base/java.lang.Thread.run(Thread.java:829)&#xD;
</failure>
      </testcase>
      <system-out/>
      <system-err/>
   </testsuite>
</testsuites>
